### PR TITLE
Page/reports

### PR DESCRIPTION
**Pull request by AlexRutledge1**
# Describe your changes
Creates the Reports page.

This page consists of two panels: 
- The modAction panel where employees can see previous action taken and navigate to moderators/moderated users profiles if they want to take a further look.
- The Reports panel where employees can see a list of reported content and take action on said content or users depending on what they choose.
image

How the modactions look when expanded:
image

Here are the popups for each moderation option:
- Absolve: 
image
- Delete:
image
- Ban:
image

# Issue ticket number and link
#28 #27

### CODE REVIEW

**Review by DanielW48 — APPROVED** [review]
Nice man. 👍

**Review by Henry-Graves — APPROVED** [review]
code looks good & I just pulled to check it all out. Very nice work! The only thing I would change is the Mod Action History interactions so that it goes: `show content -> scrollable list of only the dates where action was taken place -> click on any date to see the full list of actions taken (timestamp, mod, moderated, reason)`. It makes it easier to locate things that happened on a certain date. This is definitely MVP & good enough though, so up to you

**Comment by AlexRutledge1** [comment]
> code looks good & I just pulled to check it all out. Very nice work! The only thing I would change is the Mod Action History interactions so that it goes: `show content -> scrollable list of only the dates where action was taken place -> click on any date to see the full list of actions taken (timestamp, mod, moderated, reason)`. It makes it easier to locate things that happened on a certain date. This is definitely MVP & good enough though, so up to you

Yeah I agree, gonna work on implementing that and maybe some limited search functionality to make the experience better for employees.

**Comment by AlexRutledge1** [comment]
Just updated the PR with Henry's recommendations 👍 take another look whenever y'all get the chance

**Review by Henry-Graves — APPROVED** [review]
looks dope, here's a screenshot for anyone else interested
image

**Pull request merged**
