### PR TITLE
Backend web

### PR DESCRIPTION
**Pull request by JacobSteinebronn**
- Deploy firebase hosting
- Make a page for testing backend stuff on the web

### CODE REVIEW

**Comment by tylerhm** [comment]
I'm commenting without any knowledge about the system, but why do we need to commit .cache files?

**Comment by JacobSteinebronn** [comment]
I'm not really sure what that is, but I *think* it's for running firebase deploy, so it's *probably* fine to add to the gitignore since it's not like it's pushed to the deployment anyway

**Comment by tylerhm** [comment]
It looks like the post install breaks in CI. We probably don't need it... Can just update the submodules on our own.

**Comment by Henry-Graves** [comment]
code looks good, the GitHub Action just seems like it needs a key to access the repo

From the error log:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Review by Henry-Graves — APPROVED** [review]
LGTM, I'm fine with removing the CI

**Review by AlexRutledge1 — APPROVED** [review]
Looks good, thanks for getting ahead on firebase integration Jacob

**Pull request merged**
